update tests.yml

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -6,14 +6,17 @@ jobs:
   build:
     runs-on: ubuntu-latest
     container:
-      image: mcr.microsoft.com/playwright/java:v1.50.0-noble
+      image: mcr.microsoft.com/playwright/java:v1.50.0
     steps:
       - uses: actions/checkout@v4
+
+      - name: Check Maven repository path
+        run: ls -la /root/.m2/repository || echo "Repository not found"
 
       - name: Cache Maven repository
         uses: actions/cache@v3
         with:
-          path: ~/.m2/repository
+          path: /root/.m2/repository
           key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
           restore-keys: |
             ${{ runner.os }}-maven-
@@ -21,8 +24,8 @@ jobs:
       - name: Run tests
         run: |
           export DISPLAY=:0
-          Xvfb :0 -screen 0 1280x720x24 >/dev/null 2>&1 &  
-          mvn clean test -B
+          Xvfb :0 -screen 0 1920x1080x24 >/dev/null 2>&1 &  
+          mvn test -B
 
       - name: Upload test results
         if: always()
